{{- if not .Values.rabbitmq.enabled -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $.Release.Name }}-rabbitmq
  labels:
    app.kubernetes.io/name: {{ include "ironicStandalone.name" $ }}
    helm.sh/chart: {{ include "ironicStandalone.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
data:
  rabbitmq-password: {{ $.Values.rabbitmq.auth.password }}
  rabbitmq-erlang-cookie: {{ $.Values.rabbitmq.auth.erlangCookie }}
{{- end -}}
